
macro(ConfigureOutputDirectories root)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${root}/bin/${CMAKE_BUILD_TYPE})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${root}/lib/${CMAKE_BUILD_TYPE})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${root}/lib/${CMAKE_BUILD_TYPE})

    get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(isMultiConfig)
        foreach(cfg IN LISTS CMAKE_CONFIGURATION_TYPES)
            string(TOUPPER ${cfg} cfgUpper)
            set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${cfgUpper} ${root}/bin/${cfg})
            set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${cfgUpper} ${root}/lib/${cfg})
            set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${cfgUpper} ${root}/lib/${cfg})
        endforeach()
    else()
        string(TOUPPER ${CMAKE_BUILD_TYPE} cfgUpper)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${cfgUpper} ${root}/bin)
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${cfgUpper} ${root}/lib)
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${cfgUpper} ${root}/lib)
    endif()
endmacro()
